---
# vars file for satellite6-content_views
sat_protocol: https
sat_url_api: katello/api
sat_url: "{{ sat_protocol }}://{{ sat_hostname }}/{{ sat_url_api }}"
sat_url_foreman: "{{ sat_protocol }}://{{ sat_hostname }}/foreman_tasks/api"
sat_url_filter_task_id: "tasks?search=utf8=%E2%9C%93&search=id+%3D+"
sat_url_timeout: 180
sat_publish_description: "Automated publishing from Ansible"
sat_promote_description: "Automated promotion from Ansible"

# vars for api path
sat_api_path_content_views: "v2/content_views"
sat_api_path_content_view_versions: "v2/content_view_versions"

#General queries
query_organization_id: "results[?name=='{{ sat_org }}'].id | [0]"

#Content view queries
query_cv_id: "results[?name=='{{ sat_cv_name }}'].id | [0]"
query_cv_not_composite: "results[?composite=='false'].id | [0]"
query_cv_version_list: "versions[*].{id: id, version: version, environment_ids: environment_ids, published: published}"
query_cv_latest_version_id: "results[?id=={{ item }}].versions[*].environment_ids"

#Composite content view queries
query_ccv_component_labels_list: "components[*].content_view.label"
query_ccv_cv_version_list: "results[?label=='{{ item }}'].versions[*].{id: id, environment_ids: environment_ids} | [0]"

#Tasks queries
query_tasks_get_state: "results[?id=='{{ sat_cv_task_id }}'].state | [0]"
query_tasks_get_result: "results[?id=='{{ sat_cv_task_id }}'].result | [0]"

#Environment queries
query_env_prior: "results[?name=='{{ sat_current_env_name }}'].prior.name | [0]"
query_env_id: "results[?name=='{{ sat_current_env_name }}'].id | [0]"
query_env_is_promoted: "environments[?id=='{{ sat_env_id }}'] | [0]"
