---
language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=2.0.0
  - ANSIBLE_VERSION=2.1.0
  - ANSIBLE_VERSION=2.2.0
  - ANSIBLE_VERSION=2.3.0
  - ANSIBLE_VERSION=2.4.0
  - ANSIBLE_VERSION=2.5.0
  - ANSIBLE_VERSION=2.6.0
  - ANSIBLE_VERSION=latest

before_install:
  - sudo apt-get update -qq

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - pip install ansible-lint
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Syntax check
  - "ansible-playbook -i localhost, tests/test_include_role.yml --syntax-check"
  - "ansible-lint ./"
  
notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
